### ISSUE TITLE
AssetNotFoundException thrown by SharpDX.Toolkit.dll for Arial24

### ISSUE THREAD

**Issue by damianperera** [rolandsmeenk/HolographicStudio#1]
An **AssetNotFoundExecption** is thrown by the **SharpDX.Toolkit.dll** for the **Arial24** font that is loaded in the **TweakableManager** (line 167).

The Content folder and the Arial24.xml file is present in the Project Structure, however a Arial24.bmp file is not created during the build process, which might be the reason the Toolkit throws the exception.

Find below the output from the Debug process.

``` bash
The thread 0x17dc has exited with code 0 (0x0).
The thread 0x28b4 has exited with code 0 (0x0).
Exception thrown: 'SharpDX.Toolkit.Content.AssetNotFoundException' in SharpDX.Toolkit.dll
The thread 0x1064 has exited with code 0 (0x0).
The thread 0xb34 has exited with code 0 (0x0).
Fatal exception occured
   at SharpDX.Toolkit.Content.ContentManager.FindStream(String assetName)
   at SharpDX.Toolkit.Content.ContentManager.Load(Type assetType, String assetName, Object options)
   at SharpDX.Toolkit.Content.ContentManager.Load[T](String assetName, Object options)
   at HolographicStudio.Tweakables.TweakableManager.LoadContent() in E:\Projects\Mixed Reality\Holographic Studio\HolographicStudio\Tweakables\TweakableManager.cs:line 167
   at SharpDX.Toolkit.Game.LoadContentSystems()
   at SharpDX.Toolkit.Game.LoadContent()
   at HolographicStudio.HoloStudio.LoadContent() in E:\Projects\Mixed Reality\Holographic Studio\HolographicStudio\HoloStudio.cs:line 134
   at SharpDX.Toolkit.Game.InitializeBeforeRun()
   at SharpDX.Toolkit.GameWindowDesktop.RunRenderLoop()
   at SharpDX.Toolkit.Game.Run(GameContext gameContext)
   at HolographicStudio.Program.Main() in E:\Projects\Mixed Reality\Holographic Studio\HolographicStudio\Program.cs:line 28
The program '[10924] HolographicStudio.vshost.exe' has exited with code 0 (0x0).
```

**Comment by rolandsmeenk** [comment]
The Arial24.xml has a build action "ToolkitFont" that generates a .tkb file in the output folder. Do you have a Arial24.tkb file in the debug/Content or release/Content folder after building?

**Comment by damianperera** [comment]
The output folder (HolographicStudio\bin\Debug) does not have a Content folder in it, and a Arial24.tkb file is not generated as well.

**Comment by rolandsmeenk** [comment]
Hmm, are there any .tkb files generated in the obj/Debug/Content or object/Release/Content folders?

**Comment by damianperera** [comment]
There isn't a Content folder inside obj/Debug. Please find attached a screenshot of the respective folder.

![capture](https://cloud.githubusercontent.com/assets/15967502/19852474/775f0bb2-9f89-11e6-9026-7733c2fc133c.PNG)

**Comment by rolandsmeenk** [comment]
Ok, looks like the Custom Build Actions are not functioning. These build actions are defined in the SharpDX.Toolkit.targets file that is referenced in the HolographicStudio.csproj project file. Is your project file modified?

**Comment by damianperera** [comment]
It seems so. Might I ask what version of Visual Studio are you using? And how exactly is this project configured to build? It is missing a VS solution file.

**Comment by rolandsmeenk** [comment]
I am using Visual Studio 2015. Yes, I noticed that I did not add a
solution. Probably because it also includes my version of the
ProCamEnsembleCalibrationLib project (which basically contains is in the PR
for RoomAliveTk)
I just added the solution. :) You will have to manually refer it to
the ProCamEnsembleCalibrationLib assembly it needs to use. To build that I
am using my fork of the RoomAlive TK.
